apiVersion: v1
kind: Service
metadata:
  name: iampod-springboot-service
spec:
  selector:
    app: iampod-springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
